<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Error 404</title>
    <link rel="stylesheet" href="../../../style/font/font.css">
    <style>
        html, body {
            margin: 0;
            padding: 0;
            overflow: hidden;
            font-family: monospace;
        }

        .error {
            display: flex;
            overflow: hidden;
            padding: 5vmin 5vw;
            align-items: center;
            background-color: #FFF;
            justify-content: center;
            height: calc(100vh - 10vmin);
        }

        .error-row {
            text-align: center;
        }

        .error-head > h1 {
            color: #FF0000;
            font-size: 6vmin;
            font-weight: 600 !important;
        }

        .error-text > h3 {
            margin: 2vmin 0;
            font-size: 2.5vmin;
            font-weight: 400 !important;
        }
    </style>
</head>
<body>
<div class="error">
    <div class="error-row">
        <div class="error-head">
            <h1>ERROR 404</h1>
        </div>
        <div class="error-text">
            <h3>This page does not exist!</h3>
            <h3>You will be redirected to the homepage.</h3>
        </div>
    </div>
</div>
</body>
</html>