<!-- Add these links below to the index/css.phml file in the view folder when using any of the add-ons listed-->

<!--Icons-->
<link rel="stylesheet" href="<?= $this->url('style/css/icons/brands.min.css') ?>">
<link rel="stylesheet" href="<?= $this->url('style/css/icons/fontawesome.min.css') ?>">
<link rel="stylesheet" href="<?= $this->url('style/css/icons/regular.min.css') ?>">
<link rel="stylesheet" href="<?= $this->url('style/css/icons/solid.min.css') ?>">

<!--Hamburgers-->
<link rel="stylesheet" href="<?= $this->url('style/css/hamburgers.min.css') ?>">