<!--Add these scripts below to the view/parts/js.phtml file if you use any of the listed add-ons-->

<!--Icons-->
<script type="text/javascript" src="<?= $this->url('js/icons/brands.min.js') ?>"></script>
<script type="text/javascript" src="<?= $this->url('js/icons/fontawesome.min.js') ?>"></script>
<script type="text/javascript" src="<?= $this->url('js/icons/regular.min.js') ?>"></script>
<script type="text/javascript" src="<?= $this->url('js/icons/solid.min.js') ?>"></script>

<!--reCaptcha-->
<script src="https://www.google.com/recaptcha/api.js?render=<?= SITEKEY ?>"></script>