<!--Copyright and author-->
<meta name="copyright" content="&copy; IJuanTM"/>
<meta name="author" lang="en" content="Iwan van der Wal"/>

<!--Description and keywords-->
<meta name="description" content="Simpl is an HTML, PHP, CSS, SCSS and JavaScript framework!">
<meta name="keywords" content="Simpl, HTML, PHP, CSS, SCSS, JavaScript, Framework">

<!--Set charset-->
<meta charset="utf-8">

<!--IE support-->
<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE9">

<!--Set viewport-->
<meta name="viewport" content="width=device-width, initial-scale=1">

<!--Theme color-->
<meta name="msapplication-TileColor" content="#FFFFFF">
<meta name="theme-color" content="#FFFFFF">